# Generated by Django 5.2 on 2025-05-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('ETUDIANT', 'Etudiant'), ('ALUMNI', 'Alumni'), ('ADMIN', 'Admin')], max_length=10, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('biographie', models.TextField(blank=True, max_length=45, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_activite', models.CharField(blank=True, max_length=45, null=True)),
                ('situation_pro', models.CharField(choices=[('emploi', 'En emploi'), ('stage', 'En stage'), ('chomage', "En recherche d'emploi"), ('formation', 'En formation'), ('autre', 'Autre')], max_length=15)),
                ('poste_actuel', models.CharField(blank=True, choices=[('Marketing et Ventes', [('chef_produit', 'Chef de produit'), ('responsable_marketing', 'Responsable marketing'), ('commercial_terrain', 'Commercial terrain'), ('category_manager', 'Category manager'), ('chef_ventes', 'Chef des ventes')]), ('Ressources Humaines', [('charge_recrutement', 'Chargé de recrutement'), ('gestionnaire_paie', 'Gestionnaire de paie'), ('responsable_formation', 'Responsable formation'), ('charge_relations_sociales', 'Chargé des relations sociales'), ('consultant_rh', 'Consultant RH')]), ('Comptabilité Finance', [('comptable_general', 'Comptable général'), ('controleur_gestion', 'Contrôleur de gestion'), ('auditeur_financier', 'Auditeur financier'), ('analyste_financier', 'Analyste financier'), ('tresorier_entreprise', 'Trésorier d’entreprise')]), ('Marketing Digital', [('community_manager', 'Community manager'), ('traffic_manager', 'Traffic manager'), ('seo_sea_manager', 'SEO/SEA manager'), ('growth_hacker', 'Growth hacker'), ('responsable_emailing', 'Responsable e-mailing')]), ('Communication', [('charge_communication', 'Chargé de communication'), ('attache_presse', 'Attaché de presse'), ('directeur_communication', 'Directeur de la communication'), ('concepteur_redacteur', 'Concepteur-rédacteur'), ('event_manager', 'Event manager')]), ('Logistique et Transport', [('responsable_logistique', 'Responsable logistique'), ('planificateur_transport', 'Planificateur transport'), ('gestionnaire_entrepot', 'Gestionnaire d’entrepôt'), ('chef_quai', 'Chef de quai'), ('coordinateur_supply_chain', 'Coordinateur supply chain')]), ('Informatique, Réseaux et Télécommunications', [('admin_sys_reseaux', 'Administrateur systèmes et réseaux'), ('ingenieur_telecoms', 'Ingénieur télécoms'), ('developpeur_logiciel', 'Développeur logiciel'), ('ingenieur_cybersecurite', 'Ingénieur cybersécurité'), ('architecte_cloud', 'Architecte cloud')]), ('Relations Internationales & Diplomatie', [('attache_diplomatique', 'Attaché diplomatique'), ('charge_mission_internationale', 'Chargé de mission internationale'), ('analyste_geopolitique', 'Analyste géopolitique'), ('coordinateur_ong', 'Coordinateur ONG'), ('conseiller_ri', 'Conseiller en relations publiques internationales')]), ('Autres', [('autres', 'Autres')])], max_length=45, null=True)),
                ('nom_entreprise', models.CharField(blank=True, max_length=45, null=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiere.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=8)),
                ('annee_entree', models.PositiveIntegerField(choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')])),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='filiere.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcoursAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=45)),
                ('institution', models.CharField(max_length=45)),
                ('annee_obtention', models.PositiveIntegerField()),
                ('mention', models.CharField(blank=True, choices=[('mention_passable', 'Mention Passable'), ('mention_assez_bien', 'Mention Assez Bien'), ('mention_bien', 'Mention Bien'), ('mention_tres_bien', 'Mention Très Bien')], max_length=45, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_academiques', to='accounts.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='ParcoursProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=45)),
                ('entreprise', models.CharField(max_length=45)),
                ('date_debut', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_professionnels', to='accounts.alumni')),
            ],
        ),
    ]
