# Generated by Django 5.2 on 2025-05-18 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('ETUDIANT', 'Etudiant'), ('ALUMNI', 'Alumni'), ('ADMIN', 'Admin')], max_length=10, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('biographie', models.TextField(blank=True, max_length=45, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin_cycle', models.DateField()),
                ('mention', models.CharField(blank=True, choices=[('mention_passable', 'Mention Passable'), ('mention_assez_bien', 'Mention Assez Bien'), ('mention_bien', 'Mention Bien'), ('mention_tres_bien', 'Mention Très Bien')], max_length=45, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=45, null=True)),
                ('situation_pro', models.CharField(choices=[('emploi', 'En emploi'), ('stage', 'En stage'), ('chomage', "En recherche d'emploi"), ('formation', 'En formation'), ('autre', 'Autre')], max_length=15)),
                ('poste_actuel', models.CharField(blank=True, max_length=45, null=True)),
                ('nom_entreprise', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=8)),
                ('annee_entree', models.PositiveIntegerField(choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')])),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiere.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcoursAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=45)),
                ('institution', models.CharField(max_length=45)),
                ('annee_obtention', models.PositiveIntegerField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_academiques', to='accounts.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='ParcoursProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=45)),
                ('entreprise', models.CharField(max_length=45)),
                ('date_debut', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_professionnels', to='accounts.alumni')),
            ],
        ),
    ]
