# Generated by Django 5.2 on 2025-05-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='date_fin_cycle',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='mention',
        ),
        migrations.AddField(
            model_name='alumni',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiere.filiere'),
        ),
        migrations.AddField(
            model_name='parcoursacademique',
            name='mention',
            field=models.CharField(blank=True, choices=[('mention_passable', 'Mention Passable'), ('mention_assez_bien', 'Mention Assez Bien'), ('mention_bien', 'Mention Bien'), ('mention_tres_bien', 'Mention Très Bien')], max_length=45, null=True),
        ),
    ]
