# Generated by Django 5.2 on 2025-05-31 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnis', to='filiere.filiere'),
        ),
    ]
