# Generated by Django 5.2 on 2025-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parcoursacademique_parcoursprofessionnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('etudiant', 'Étudiant'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
