# Generated by Django 5.2 on 2025-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_alumni_poste_actuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biographie',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
