# Generated by Django 5.2 on 2025-05-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcoursprofessionnel',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcoursprofessionnel',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='autre', max_length=15),
        ),
    ]
