# Generated by Django 5.2 on 2025-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_parcoursprofessionnel_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='mention',
            field=models.CharField(blank=True, choices=[('mention_passable', 'Mention Passable'), ('mention_assez_bien', 'Mention Assez Bien'), ('mention_bien', 'Mention Bien'), ('mention_tres_bien', 'Mention Très Bien')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ALUMNI', 'Alumni'), ('ADMIN', 'Admin')], default='ETUDIANT', max_length=10),
        ),
    ]
