# Generated by Django 5.2 on 2025-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_biographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biographie',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
