# Generated by Django 5.2 on 2025-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_biographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biographie',
            field=models.TextField(blank=True, default='', max_length=45),
        ),
    ]
