# Generated by Django 5.2 on 2025-06-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
