# Generated by Django 5.2 on 2025-05-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcoursAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=45)),
                ('institution', models.CharField(max_length=45)),
                ('annee_obtention', models.PositiveIntegerField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_academiques', to='accounts.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='ParcoursProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=45)),
                ('entreprise', models.CharField(max_length=45)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_professionnels', to='accounts.alumni')),
            ],
        ),
        migrations.DeleteModel(
            name='Parcours',
        ),
    ]
