# Generated by Django 5.2 on 2025-06-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groupes/'),
        ),
    ]
