# Generated by Django 5.2 on 2025-06-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_customuser_biographie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_trouve_emploi', models.BooleanField()),
                ('date_debut_emploi', models.DateField(blank=True, null=True)),
                ('domaine', models.CharField(choices=[('informatique', 'Informatique'), ('reseaux', 'Réseaux'), ('telecoms', 'Télécoms'), ('gestion', 'Science de gestion'), ('droit', 'Droit'), ('autre', 'Autre')], max_length=50)),
                ('autre_domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('note_insertion', models.IntegerField()),
                ('suggestions', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reponse_enquete', to='accounts.alumni')),
            ],
        ),
    ]
