"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidePanel from "../components/ui/side-panel";
import { usePathname, useRouter } from "next/navigation";
import { AuthProvider, useAuth } from "@/lib/api/authContext";
import { useEffect } from "react";
import { ThemeProvider } from "next-themes";
import { ProfileModalProvider } from '@/contexts/ProfileModalContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showSidePanel =
    pathname !== "/auth/login" && pathname !== "/auth/signIn";
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="data-theme" defaultTheme="light" enableSystem={false}>
          <AuthProvider>
            <ProfileModalProvider>
              <AuthGuard>
                {showSidePanel ? <SidePanel>{children}</SidePanel> : children}
              </AuthGuard>
            </ProfileModalProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

function AuthGuard({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth();
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    if (!loading && !user && pathname !== "/auth/signIn") {
      router.push("/auth/login");
    }
  }, [loading, user, pathname, router]);

  if (loading) {
    return null;
  }

  return <>{children}</>;
}
